### ISSUE TITLE
FEATURE REQUEST: Custom `onDisconnect`?

### ISSUE THREAD

**Issue by iTonyYo** [tshaddix/webext-redux#128]
I want to clear store when the popup is closed.
The `port.onDisconnect` will be fired in background page.
It would be great if you could do that.
Or is there any better advice? I sincerely!

**Comment by tshaddix** [comment]
@iTonyYo Got it! This use case makes sense. I don't envision it being too difficult to expose the created port via `wrapStore`. 

In the meantime, you might consider listening to https://developer.mozilla.org/en-US/docs/Web/Events/beforeunload in your popup page and shooting off an event to indicate the popup is closing.

**Comment by vhmth** [comment]
@iTonyYo is there a reason to use `onDisconnect` vs. `beforeunload`? We actually do something similar in the Loom Chrome extension where we listen to beforeunload and dispatch some actions on the background and popup pages.

I'm not asking to be a jerk - just trying to understand the use case. :-P I would vote more towards not exposing `onDisconnect` if possible since this further leaks the connection object outside of this API. I get that it'd be useful though, so I'm not trying to be a purist either by any means.

**Comment by dylanjt** [comment]
Hmm. Given this code:

```
componentDidMount() {
    const background = chrome.extension.getBackgroundPage()
    const resetState = this.props.resetState
    addEventListener("unload", function (event) {
        resetState()
        background.console.log(event.type)
    }, true)
}
```

I can see the 'unload' event console.logged in my background page when the popover closes, but unfortunately my resetState() action never seems to fire. My reducer / redux-logic lives in the background page, while that above component is in the Popover. @iTonyYo at a cursory glance, have I architectured anything wrong? My best guess here is that the resetState() event fire doesn't make it all the way through the port to my background page before its execution environment (the popover) is trashed.

Any ideas? The problem I'm facing requires the popover have a clean slate every time it's opened - the "right" way to do this would be to reset the reducer on popover close. But Chrome seems to make this ridiculously difficult to accomplish, unless I'm missing something very obvious here.

**Comment by ethanroday** [comment]
@iTonyYo See #155 - you can always open a separate port on popup initialization and listen for the disconnect in the background.
